// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func OpenImageViewer(attachmentID int64) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_OpenImageViewer_cbf4`,
		Function: `function __templ_OpenImageViewer_cbf4(attachmentID){// Close any existing image viewer
    var dialog = document.querySelector('dialog[name="image-viewer"]');
    if (dialog) dialog.close();

    var imageURL = ` + "`" + `./trouble-reports/attachments?attachment_id=${attachmentID}` + "`" + `;
    var imageViewer = document.querySelector('template[name="image-viewer"]');
    dialog = imageViewer.content.cloneNode(true).querySelector('dialog');
    var img = dialog.querySelector('img.attachment');
    var closeButton = dialog.querySelector('button.close');

    console.debug(` + "`" + `Opening image viewer with image ${imageURL}` + "`" + `);

    img.src = imageURL;
    img.onclick = function(event) {
        event.stopPropagation();
    };

    dialog.onclick = function() {
        dialog.close();
    };

    closeButton.onclick = function() {
        dialog.close();
    };

    dialog.onclose = function(event) {
        document.body.removeChild(dialog);
        dialog = undefined
    };

    document.body.appendChild(dialog);
    dialog.showModal();
}`,
		Call:       templ.SafeScript(`__templ_OpenImageViewer_cbf4`, attachmentID),
		CallInline: templ.SafeScriptInline(`__templ_OpenImageViewer_cbf4`, attachmentID),
	}
}

var _ = templruntime.GeneratedTemplate
